### ISSUE TITLE
XAudio throws exceptions when try to playback audio from ffmpeg.

### ISSUE THREAD

**Issue by Sebanisu** [MaKiPL/OpenVIII#101]
Effects Direct3D build
XAudio throws exceptions when try to playback audio from ffmpeg.

related? https://github.com/MonoGame/MonoGame/issues/5662

**Comment by Sebanisu** [comment]
`SharpDX.SharpDXException
  HResult=0x88960001
  Message=HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
  Source=SharpDX
  StackTrace:
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, IntPtr bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.PlatformSubmitBuffer(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.SubmitBuffer(Byte[] buffer, Int32 offset, Int32 count)
   at FF8.Ffcc.LoadSoundFromStream(Byte[]& buffer, Int32 start, Int32& length) in D:\OpenVIII\FF8\Ffcc.cs:line 965
   at FF8.Ffcc.WritetoMs(Byte[]& output, Int32 start, Int32& length) in D:\OpenVIII\FF8\Ffcc.cs:line 1349
   at FF8.Ffcc.Resample(AVFrame& frame) in D:\OpenVIII\FF8\Ffcc.cs:line 1255
   at FF8.Ffcc.Process() in D:\OpenVIII\FF8\Ffcc.cs:line 1201
   at FF8.Ffcc.PrepareProcess() in D:\OpenVIII\FF8\Ffcc.cs:line 1100
   at FF8.Ffcc.Update(FfccState state, Int32 ret) in D:\OpenVIII\FF8\Ffcc.cs:line 1323
   at FF8.Ffcc.Init(String filename, AVMediaType mediatype, FfccMode mode, Int32 loopstart) in D:\OpenVIII\FF8\Ffcc.cs:line 883
   at FF8.Ffcc..ctor(String filename, AVMediaType mediatype, FfccMode mode, Int32 loopstart) in D:\OpenVIII\FF8\Ffcc.cs:line 69
   at FF8.Module_movie_test.LoadMovie() in D:\OpenVIII\FF8\module_movie_test.cs:line 197
   at FF8.Module_movie_test.Update() in D:\OpenVIII\FF8\module_movie_test.cs:line 102
   at FF8.ModuleHandler.<Update>d__2.MoveNext() in D:\OpenVIII\FF8\ModuleHandler.cs:line 68
`

**Comment by benjaminfoo** [comment]
Im glad my thoughts worked on this :) - I'm getting the exact same results however.

**Comment by Sebanisu** [comment]
so you select directx project and it didn't work?

**Comment by benjaminfoo** [comment]
As I've developed this on my own, yes - I haven't tried your latest commit for now, I'll test it tomorrow but I think it should work - I've also disabled the audio previously and it worked.

**Comment by Sebanisu** [comment]
I might wanna see if naudio can help make things work. I was avoiding it because some of it's functions are windows only and i was going ffmpeg -> monogame so why add another layer. Though we still have the library there so maybe it can eat the audio samples and spit it out of waveout or directsound. instead of xaudio.

**Comment by Sebanisu** [comment]
https://github.com/MonoGame/MonoGame/issues/6611 per this issue sharpdx is a discontinued project monogame was using to interface with xaudio.  Resent 21 day old post says they forked it.  So maybe a fix will happen when they update it.

**Comment by benjaminfoo** [comment]
After setting the target-platform to x86 everywhere it worked - I guess the midi-sounds are still played (hearable at the black/white intro, not working in the first amv-intro).

**Comment by Sebanisu** [comment]
yeah midi only works in x86. because it uses an old library. Maki is working on replacing it. 
https://github.com/MaKiPL/OpenVIII/issues/7
They have it replaced in linux but having trouble compiling the new library in Windows.

**Comment by Sebanisu** [comment]
https://stackoverflow.com/questions/6377597/streaming-non-pcm-raw-audio-using-naudio

I think this is promising info though it's been a while since I've messed with ffcc. I basically need to take any part that writes to a SoundEffect or DynamicSoundEffectInstance and say when error occured use naudio calls instead.

Another thought was we build monogram ourselves and use desktopgl's audio with everything else windows. Though I haven't a clue how difficult that would be.

**Comment by Sebanisu** [comment]
Maybe I should make a wrapper class that holds all the soundeffects or dynamic sounds and naudio and just presents a dumbed down interface for ffcc or other libraries to use.

**Comment by Sebanisu** [comment]
https://markheath.net/post/how-to-record-and-play-audio-at-same <- this looks like exactly what I need.

**Comment by Sebanisu** [comment]
Okay I added workaround till monogame fixes SharpDX.XAudio2. Though maybe there's a better way I haven't found. When it detects the above exception it switches to nAudio mode. And all audio is piped through that into DirectSoundOut. It's not perfect. Sometimes the sound glitches. But it seems to be working.
